FLAGS      = -std=c++11
CPP_DEFS   = -D=HAVE_CONFIG_H
CPP_OPTS   = -Wall -O2

# all: wertyu.cpp peskyPali.cpp google_lucky.cpp train_connector.cpp
# all: onetwothree.cpp pruneList.cpp
	# g++ $(FLAGS) ${CPP_OPTS} ${CPP_DEFS} -o wertyu wertyu.cpp
	# g++ $(FLAGS) ${CPP_OPTS} ${CPP_DEFS} -o LC_Display LC_Display.cpp
	# g++ $(FLAGS) ${CPP_OPTS} ${CPP_DEFS} -o peskyPali peskyPali.cpp
	# g++ $(FLAGS) ${CPP_OPTS} ${CPP_DEFS} -o google_lucky google_lucky.cpp
	# g++ $(FLAGS) ${CPP_OPTS} ${CPP_DEFS} -o train_connector train_connector.cpp
	# g++ $(FLAGS) ${CPP_OPTS} ${CPP_DEFS} -o onetwothree onetwothree.cpp
	# g++ $(FLAGS) ${CPP_OPTS} ${CPP_DEFS} -o pruneList pruneList.cpp

clean:
	rm -f all